// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onUltrasonicChange();
void onLEDChange();

float ultrasonic;
bool lED;

void initProperties(){

  ArduinoCloud.addProperty(ultrasonic, READWRITE, ON_CHANGE, onUltrasonicChange, 20);
  ArduinoCloud.addProperty(lED, READWRITE, ON_CHANGE, onLEDChange);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
